version: "3.8"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrestestpass
      POSTGRES_USER: postgrestestuser
      POSTGRES_DB: testdb
volumes:
  postgres:
