app_rg_location    = "japaneast"
app_rg_name        = "rg-db-retry001"
app_acr_name       = "acrdbretry001"
app_pg_server_name = "pgdbretry001"
app_pg_db_name     = "app_db_production"
log_analytics_workspace_name = "log-miyohide-ws001"
