name: Create and push Docker Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: create Docker Image for retry_sample
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///')
          cd retry_sample
          ./gradlew bootBuildImage --imageName=${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG
          docker push ${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG
          docker tag ${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG ${{ secrets.REGISTRY_SERVER }}/retry_db:latest
          docker push ${{ secrets.REGISTRY_SERVER }}/retry_db:latest
      - name: create Docker Image for non_retry_sample
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///')
          cd non_retry_sample
          ./gradlew bootBuildImage --imageName=${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG
          docker push ${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG
          docker tag ${{ secrets.REGISTRY_SERVER }}/retry_db:$IMAGE_TAG ${{ secrets.REGISTRY_SERVER }}/retry_db:latest
          docker push ${{ secrets.REGISTRY_SERVER }}/retry_db:latest
